name: Node.js CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpx playwright install

      - name: Run tests
        run: pnpm test

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login dr.aleksivirkkala.com -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t dr.aleksivirkkala.com/${{ github.event.repository.name }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push dr.aleksivirkkala.com/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Call webhook to trigger deployment
        run: curl -X POST ${{ secrets.WEBHOOK_URL }}
